using System.Text;
using Markdn.SourceGenerators.Models;

namespace Markdn.SourceGenerators.Emitters;

/// <summary>
/// Emits C# source code for Blazor components from ComponentMetadata.
/// Handles class structure, namespace, attributes, inheritance, and parameters.
/// </summary>
public static class ComponentCodeEmitter
{
    /// <summary>
    /// Generate complete component source code.
    /// </summary>
    /// <param name="componentName">Component class name</param>
    /// <param name="namespaceValue">Namespace for the component</param>
    /// <param name="htmlContent">Rendered HTML content</param>
    /// <param name="metadata">Component metadata from YAML front matter</param>
    /// <returns>Complete C# source code</returns>
    public static string Emit(
        string componentName,
        string namespaceValue,
        string htmlContent,
        ComponentMetadata metadata)
    {
        var sb = new StringBuilder();
        
        // File header
        sb.AppendLine("// <auto-generated by Markdn.SourceGenerators v1.0.0 />");
        sb.AppendLine("// This file is auto-generated. Do not edit directly.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Using directives (from metadata)
        if (metadata.Using != null && metadata.Using.Count > 0)
        {
            foreach (var usingDirective in metadata.Using)
            {
                sb.AppendLine($"using {usingDirective};");
            }
            sb.AppendLine();
        }

        // Namespace
        sb.AppendLine($"namespace {namespaceValue}");
        sb.AppendLine("{");

        // Route attributes (T046, T047: from metadata Url/UrlArray)
        if (!string.IsNullOrEmpty(metadata.Url))
        {
            sb.AppendLine($"    [Microsoft.AspNetCore.Components.RouteAttribute(\"{metadata.Url}\")]");
        }
        else if (metadata.UrlArray != null && metadata.UrlArray.Count > 0)
        {
            foreach (var url in metadata.UrlArray)
            {
                sb.AppendLine($"    [Microsoft.AspNetCore.Components.RouteAttribute(\"{url}\")]");
            }
        }

        // Class attributes (from metadata)
        if (metadata.Attribute != null && metadata.Attribute.Count > 0)
        {
            foreach (var attribute in metadata.Attribute)
            {
                sb.AppendLine($"    [{attribute}]");
            }
        }

        // Class declaration with inheritance
        var baseClass = metadata.Inherit ?? "Microsoft.AspNetCore.Components.ComponentBase";
        sb.AppendLine($"    public partial class {componentName} : {baseClass}");
        sb.AppendLine("    {");

        // Component parameters
        if (metadata.Parameters != null && metadata.Parameters.Count > 0)
        {
            foreach (var parameter in metadata.Parameters)
            {
                sb.AppendLine("        [Microsoft.AspNetCore.Components.Parameter]");
                sb.AppendLine($"        public {parameter.Type} {parameter.Name} {{ get; set; }}");
                sb.AppendLine();
            }
        }

        // BuildRenderTree method (using RenderTreeBuilderEmitter)
        sb.Append(RenderTreeBuilderEmitter.EmitBuildRenderTree(htmlContent, indentLevel: 2));

        // Close class and namespace
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generate simple component source (legacy method for backward compatibility).
    /// </summary>
    public static string EmitSimple(
        string componentName,
        string namespaceValue,
        string htmlContent)
    {
        return Emit(componentName, namespaceValue, htmlContent, ComponentMetadata.Empty);
    }
}
