param(
    [int]$Count = 100
)

$project = "src/Markdn.Blazor.App/Markdn.Blazor.App.csproj"
$pagesDir = "src/Markdn.Blazor.App/Pages/Blog"

Write-Host "Preparing $Count markdown files in $pagesDir"
New-Item -ItemType Directory -Force -Path $pagesDir | Out-Null

for ($i = 1; $i -le $Count; $i++) {
    $name = "{0:000}" -f $i
    $path = Join-Path $pagesDir "post-$name.md"
    $content = @"
---
title: "Test Post $i"
date: 2025-11-11
---

# Test Post $i

This is autogenerated content for performance testing.

Reference a component: <Counter />

Content index: $i

"@
    Set-Content -Path $path -Value $content -Encoding UTF8
}

Write-Host "Starting build of $project and measuring time..."
$elapsed = Measure-Command { dotnet build $project --nologo }
Write-Host "Build elapsed: $($elapsed.TotalSeconds) seconds"

# Check for generated files (*.md.g.cs) under obj
$objDir = "src/Markdn.Blazor.App/obj"
$generated = Get-ChildItem -Path $objDir -Recurse -Filter "*.md.g.cs" -ErrorAction SilentlyContinue
if ($null -eq $generated) {
    Write-Host "No generated .md.g.cs files found under $objDir"
    exit 1
}
else {
    Write-Host "Found $($generated.Count) generated .md.g.cs files. Sample:"
    $generated | Select-Object -First 5 | ForEach-Object { Write-Host $_.FullName }
}

# Print summary
[PSCustomObject]@{
    MarkdownFilesCreated = $Count
    BuildSeconds = $elapsed.TotalSeconds
    GeneratedFilesFound = $generated.Count
} | ConvertTo-Json -Depth 3
